using UnityEngine;

public class SoundEffectManager : MonoBehaviour {
    public static SoundEffectManager Instance;

    [SerializeField] private AudioSource soundFXObject;
    [SerializeField] private AudioSource musicObject;

    private void Awake() {
        if (Instance == null) {
            Instance = this;
        }
    }

    private void OnDestroy() {
        if (Instance == this) Instance = null;
    }

    public AudioSource PlaySoundFXClip(AudioClip audioClip, Transform spawnTransform, float volume) {
        // spawn in gameobject
        AudioSource audioSource = Instantiate(soundFXObject, spawnTransform.position, Quaternion.identity);

        // assign the audioClip
        audioSource.clip = audioClip;

        // assign volume
        audioSource.volume = volume;

        // play sound
        audioSource.Play();

        // get length of sound FX clip
        float clipLength = audioSource.clip.length;

        // destroy clip after its done playing
        Destroy(audioSource.gameObject, clipLength);
        return audioSource;
    }

    public AudioSource PlayRandomSoundFXClip(AudioClip[] audioClip, Transform spawnTransform, float volume) {
        // assign random index
        int randomIndex = Random.Range(0, audioClip.Length);

        // spawn in gameobject
        AudioSource audioSource = Instantiate(soundFXObject, spawnTransform.position, Quaternion.identity);

        // assign the audioClip
        audioSource.clip = audioClip[randomIndex];

        // assign volume
        audioSource.volume = volume;

        // play sound
        audioSource.Play();

        // get length of sound FX clip
        float clipLength = audioSource.clip.length;

        // destroy clip after its done playing
        Destroy(audioSource.gameObject, clipLength);
        return audioSource;
    }

    public void PlayLoopingMusic(AudioClip audioClip, Transform spawnTransform, float volume) {
        // spawn in gameobject
        AudioSource audioSource = Instantiate(musicObject, spawnTransform.position, Quaternion.identity);

        // assign the audioClip
        audioSource.clip = audioClip;

        // assign volume
        audioSource.volume = volume;

        // play sound
        audioSource.Play();
    }
}
